server:
  port: 41111

spring:
  redis:
    database: 0
    host: 47.98.237.88
    port: 6379
    # 连接超时时间 单位 ms（毫秒
    timeout: 3000
    password: sunchao
    pool:
      # 连接池中的最大空闲连接，默认值也是8。
      max-idle: 8
      #连接池中的最小空闲连接，默认值也是0。
      min-idle: 0
      # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
      max-active: 8
      # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
      max-wait: 10000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.237.88:3306/deposit_managedemo?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true

mybatis:
  mapper-locations: classpath*:com/personal/dao/*.xml