server:
  port: 41111

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deposit_managedemo?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true

mybatis:
  mapper-locations: classpath*:com/personal/dao/*.xml